sudo: required
dist: trusty
language: cpp
compiler: gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq pkg-config qt5-qmake qtbase5-dev
before_script:
    - qmake -qt=qt5 -r -v
    - qmake -qt=qt5 -r
    - make
script: make check TESTRUNNER=\"LD_LIBRARY_PATH=$(pwd)/perf/ sh -c \"
branches:
    only:
        - master
notifications:
    recipients:
        - francis.giraldeau@gmail.com
    email:
        on_failure: always
